namespace ProjectLEGO.Desktop;

partial class MainForm
{
    private System.ComponentModel.IContainer components = null!;
    private TabControl mainTabControl = null!;
    private TabPage registrationTabPage = null!;
    private TabPage callTabPage = null!;
    private TableLayoutPanel registrationLayout = null!;
    private Label registrationTitleLabel = null!;
    private Label legoNameLabel = null!;
    private TextBox legoNameTextBox = null!;
    private Label feature1Label = null!;
    private TextBox feature1TextBox = null!;
    private Label feature2Label = null!;
    private TextBox feature2TextBox = null!;
    private Label feature3Label = null!;
    private TextBox feature3TextBox = null!;
    private Label feature4Label = null!;
    private TextBox feature4TextBox = null!;
    private FlowLayoutPanel registrationButtonPanel = null!;
    private Button registerButton = null!;
    private Button updateRegistrationButton = null!;
    private Button closeRegistrationButton = null!;
    private TableLayoutPanel callLayout = null!;
    private TableLayoutPanel searchLayout = null!;
    private Label searchLabel = null!;
    private TextBox searchTextBox = null!;
    private Button searchButton = null!;
    private TableLayoutPanel selectionLayout = null!;
    private GroupBox searchResultGroupBox = null!;
    private ListBox searchResultListBox = null!;
    private GroupBox feature1GroupBox = null!;
    private ListBox feature1ListBox = null!;
    private GroupBox feature2GroupBox = null!;
    private ListBox feature2ListBox = null!;
    private GroupBox feature3GroupBox = null!;
    private ListBox feature3ListBox = null!;
    private GroupBox feature4GroupBox = null!;
    private ListBox feature4ListBox = null!;
    private Label selectedLegoLabel = null!;
    private FlowLayoutPanel callButtonPanel = null!;
    private Button openButton = null!;
    private Button insertButton = null!;
    private Button editButton = null!;
    private Button closeCallButton = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            components?.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        mainTabControl = new TabControl();
        registrationTabPage = new TabPage();
        registrationLayout = new TableLayoutPanel();
        registrationTitleLabel = new Label();
        legoNameLabel = new Label();
        legoNameTextBox = new TextBox();
        feature1Label = new Label();
        feature1TextBox = new TextBox();
        feature2Label = new Label();
        feature2TextBox = new TextBox();
        feature3Label = new Label();
        feature3TextBox = new TextBox();
        feature4Label = new Label();
        feature4TextBox = new TextBox();
        registrationButtonPanel = new FlowLayoutPanel();
        registerButton = new Button();
        updateRegistrationButton = new Button();
        closeRegistrationButton = new Button();
        callTabPage = new TabPage();
        callLayout = new TableLayoutPanel();
        searchLayout = new TableLayoutPanel();
        searchLabel = new Label();
        searchTextBox = new TextBox();
        searchButton = new Button();
        selectionLayout = new TableLayoutPanel();
        searchResultGroupBox = new GroupBox();
        searchResultListBox = new ListBox();
        feature1GroupBox = new GroupBox();
        feature1ListBox = new ListBox();
        feature2GroupBox = new GroupBox();
        feature2ListBox = new ListBox();
        feature3GroupBox = new GroupBox();
        feature3ListBox = new ListBox();
        feature4GroupBox = new GroupBox();
        feature4ListBox = new ListBox();
        selectedLegoLabel = new Label();
        callButtonPanel = new FlowLayoutPanel();
        openButton = new Button();
        insertButton = new Button();
        editButton = new Button();
        closeCallButton = new Button();
        mainTabControl.SuspendLayout();
        registrationTabPage.SuspendLayout();
        registrationLayout.SuspendLayout();
        registrationButtonPanel.SuspendLayout();
        callTabPage.SuspendLayout();
        callLayout.SuspendLayout();
        searchLayout.SuspendLayout();
        selectionLayout.SuspendLayout();
        searchResultGroupBox.SuspendLayout();
        feature1GroupBox.SuspendLayout();
        feature2GroupBox.SuspendLayout();
        feature3GroupBox.SuspendLayout();
        feature4GroupBox.SuspendLayout();
        callButtonPanel.SuspendLayout();
        SuspendLayout();

        mainTabControl.Controls.Add(registrationTabPage);
        mainTabControl.Controls.Add(callTabPage);
        mainTabControl.Dock = DockStyle.Fill;
        mainTabControl.Font = new Font("맑은 고딕", 10F);
        mainTabControl.Location = new Point(12, 12);
        mainTabControl.Name = "mainTabControl";
        mainTabControl.SelectedIndex = 0;
        mainTabControl.Size = new Size(1256, 736);

        registrationTabPage.Controls.Add(registrationLayout);
        registrationTabPage.Location = new Point(4, 26);
        registrationTabPage.Name = "registrationTabPage";
        registrationTabPage.Padding = new Padding(28);
        registrationTabPage.Size = new Size(1248, 706);
        registrationTabPage.Text = "등록";
        registrationTabPage.UseVisualStyleBackColor = true;

        registrationLayout.ColumnCount = 3;
        registrationLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 22F));
        registrationLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 56F));
        registrationLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 22F));
        registrationLayout.Controls.Add(registrationTitleLabel, 0, 0);
        registrationLayout.Controls.Add(legoNameLabel, 0, 1);
        registrationLayout.Controls.Add(legoNameTextBox, 1, 1);
        registrationLayout.Controls.Add(feature1Label, 0, 2);
        registrationLayout.Controls.Add(feature1TextBox, 1, 2);
        registrationLayout.Controls.Add(feature2Label, 0, 3);
        registrationLayout.Controls.Add(feature2TextBox, 1, 3);
        registrationLayout.Controls.Add(feature3Label, 0, 4);
        registrationLayout.Controls.Add(feature3TextBox, 1, 4);
        registrationLayout.Controls.Add(feature4Label, 0, 5);
        registrationLayout.Controls.Add(feature4TextBox, 1, 5);
        registrationLayout.Controls.Add(registrationButtonPanel, 1, 6);
        registrationLayout.Dock = DockStyle.Fill;
        registrationLayout.RowCount = 8;
        registrationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 74F));
        registrationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 68F));
        registrationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 68F));
        registrationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 68F));
        registrationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 68F));
        registrationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 68F));
        registrationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 72F));
        registrationLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

        registrationTitleLabel.AutoSize = true;
        registrationLayout.SetColumnSpan(registrationTitleLabel, 3);
        registrationTitleLabel.Dock = DockStyle.Fill;
        registrationTitleLabel.Font = new Font("맑은 고딕", 16F, FontStyle.Bold);
        registrationTitleLabel.Text = "LEGO 등록 및 수정";
        registrationTitleLabel.TextAlign = ContentAlignment.MiddleCenter;

        legoNameLabel.Dock = DockStyle.Fill;
        legoNameLabel.Font = new Font("맑은 고딕", 10F, FontStyle.Bold);
        legoNameLabel.Text = "LEGO 이름";
        legoNameLabel.TextAlign = ContentAlignment.MiddleRight;
        feature1Label.Dock = DockStyle.Fill;
        feature1Label.Font = new Font("맑은 고딕", 10F, FontStyle.Bold);
        feature1Label.Text = "LEGO 특성1";
        feature1Label.TextAlign = ContentAlignment.MiddleRight;
        feature2Label.Dock = DockStyle.Fill;
        feature2Label.Font = new Font("맑은 고딕", 10F, FontStyle.Bold);
        feature2Label.Text = "LEGO 특성2";
        feature2Label.TextAlign = ContentAlignment.MiddleRight;
        feature3Label.Dock = DockStyle.Fill;
        feature3Label.Font = new Font("맑은 고딕", 10F, FontStyle.Bold);
        feature3Label.Text = "LEGO 특성3";
        feature3Label.TextAlign = ContentAlignment.MiddleRight;
        feature4Label.Dock = DockStyle.Fill;
        feature4Label.Font = new Font("맑은 고딕", 10F, FontStyle.Bold);
        feature4Label.Text = "LEGO 특성4";
        feature4Label.TextAlign = ContentAlignment.MiddleRight;
        legoNameTextBox.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        legoNameTextBox.Font = new Font("맑은 고딕", 11F);
        legoNameTextBox.Name = "legoNameTextBox";
        feature1TextBox.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        feature1TextBox.Font = new Font("맑은 고딕", 11F);
        feature1TextBox.Name = "feature1TextBox";
        feature2TextBox.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        feature2TextBox.Font = new Font("맑은 고딕", 11F);
        feature2TextBox.Name = "feature2TextBox";
        feature3TextBox.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        feature3TextBox.Font = new Font("맑은 고딕", 11F);
        feature3TextBox.Name = "feature3TextBox";
        feature4TextBox.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        feature4TextBox.Font = new Font("맑은 고딕", 11F);
        feature4TextBox.Name = "feature4TextBox";

        registrationButtonPanel.Controls.Add(registerButton);
        registrationButtonPanel.Controls.Add(updateRegistrationButton);
        registrationButtonPanel.Controls.Add(closeRegistrationButton);
        registrationButtonPanel.Dock = DockStyle.Fill;
        registrationButtonPanel.FlowDirection = FlowDirection.LeftToRight;
        registrationButtonPanel.Padding = new Padding(0, 12, 0, 0);
        registrationButtonPanel.WrapContents = false;
        registerButton.Height = 38;
        registerButton.Margin = new Padding(0, 0, 10, 0);
        registerButton.Text = "등록";
        registerButton.Width = 110;
        updateRegistrationButton.Height = 38;
        updateRegistrationButton.Margin = new Padding(0, 0, 10, 0);
        updateRegistrationButton.Text = "수정";
        updateRegistrationButton.Width = 110;
        closeRegistrationButton.Height = 38;
        closeRegistrationButton.Margin = new Padding(0, 0, 10, 0);
        closeRegistrationButton.Text = "닫기";
        closeRegistrationButton.Width = 110;

        callTabPage.Controls.Add(callLayout);
        callTabPage.Location = new Point(4, 26);
        callTabPage.Name = "callTabPage";
        callTabPage.Padding = new Padding(18);
        callTabPage.Size = new Size(1248, 706);
        callTabPage.Text = "호출";
        callTabPage.UseVisualStyleBackColor = true;

        callLayout.ColumnCount = 1;
        callLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        callLayout.Controls.Add(searchLayout, 0, 0);
        callLayout.Controls.Add(selectionLayout, 0, 1);
        callLayout.Controls.Add(selectedLegoLabel, 0, 2);
        callLayout.Controls.Add(callButtonPanel, 0, 3);
        callLayout.Dock = DockStyle.Fill;
        callLayout.RowCount = 4;
        callLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
        callLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        callLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        callLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 62F));

        searchLayout.ColumnCount = 3;
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100F));
        searchLayout.Controls.Add(searchLabel, 0, 0);
        searchLayout.Controls.Add(searchTextBox, 1, 0);
        searchLayout.Controls.Add(searchButton, 2, 0);
        searchLayout.Dock = DockStyle.Fill;
        searchLabel.Dock = DockStyle.Fill;
        searchLabel.Font = new Font("맑은 고딕", 10F, FontStyle.Bold);
        searchLabel.Text = "LEGO 이름 검색";
        searchLabel.TextAlign = ContentAlignment.MiddleLeft;
        searchTextBox.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        searchTextBox.Name = "searchTextBox";
        searchTextBox.PlaceholderText = "LEGO 이름 일부를 입력하세요";
        searchButton.Dock = DockStyle.Fill;
        searchButton.Margin = new Padding(8, 8, 0, 8);
        searchButton.Name = "searchButton";
        searchButton.Text = "검색";

        selectionLayout.ColumnCount = 5;
        selectionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        selectionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        selectionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        selectionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        selectionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        selectionLayout.Controls.Add(searchResultGroupBox, 0, 0);
        selectionLayout.Controls.Add(feature1GroupBox, 1, 0);
        selectionLayout.Controls.Add(feature2GroupBox, 2, 0);
        selectionLayout.Controls.Add(feature3GroupBox, 3, 0);
        selectionLayout.Controls.Add(feature4GroupBox, 4, 0);
        selectionLayout.Dock = DockStyle.Fill;
        selectionLayout.RowCount = 1;
        selectionLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

        searchResultGroupBox.Controls.Add(searchResultListBox);
        searchResultGroupBox.Dock = DockStyle.Fill;
        searchResultGroupBox.Font = new Font("맑은 고딕", 10F, FontStyle.Bold);
        searchResultGroupBox.Margin = new Padding(4);
        searchResultGroupBox.Padding = new Padding(8);
        searchResultGroupBox.Text = "검색 결과";
        searchResultListBox.Dock = DockStyle.Fill;
        searchResultListBox.Font = new Font("맑은 고딕", 10F);
        searchResultListBox.IntegralHeight = false;
        searchResultListBox.Name = "searchResultListBox";
        feature1GroupBox.Controls.Add(feature1ListBox);
        feature1GroupBox.Dock = DockStyle.Fill;
        feature1GroupBox.Font = new Font("맑은 고딕", 10F, FontStyle.Bold);
        feature1GroupBox.Margin = new Padding(4);
        feature1GroupBox.Padding = new Padding(8);
        feature1GroupBox.Text = "특성1";
        feature1ListBox.Dock = DockStyle.Fill;
        feature1ListBox.Enabled = false;
        feature1ListBox.Font = new Font("맑은 고딕", 10F);
        feature1ListBox.IntegralHeight = false;
        feature1ListBox.Name = "feature1ListBox";
        feature2GroupBox.Controls.Add(feature2ListBox);
        feature2GroupBox.Dock = DockStyle.Fill;
        feature2GroupBox.Font = new Font("맑은 고딕", 10F, FontStyle.Bold);
        feature2GroupBox.Margin = new Padding(4);
        feature2GroupBox.Padding = new Padding(8);
        feature2GroupBox.Text = "특성2";
        feature2ListBox.Dock = DockStyle.Fill;
        feature2ListBox.Enabled = false;
        feature2ListBox.Font = new Font("맑은 고딕", 10F);
        feature2ListBox.IntegralHeight = false;
        feature2ListBox.Name = "feature2ListBox";
        feature3GroupBox.Controls.Add(feature3ListBox);
        feature3GroupBox.Dock = DockStyle.Fill;
        feature3GroupBox.Font = new Font("맑은 고딕", 10F, FontStyle.Bold);
        feature3GroupBox.Margin = new Padding(4);
        feature3GroupBox.Padding = new Padding(8);
        feature3GroupBox.Text = "특성3";
        feature3ListBox.Dock = DockStyle.Fill;
        feature3ListBox.Enabled = false;
        feature3ListBox.Font = new Font("맑은 고딕", 10F);
        feature3ListBox.IntegralHeight = false;
        feature3ListBox.Name = "feature3ListBox";
        feature4GroupBox.Controls.Add(feature4ListBox);
        feature4GroupBox.Dock = DockStyle.Fill;
        feature4GroupBox.Font = new Font("맑은 고딕", 10F, FontStyle.Bold);
        feature4GroupBox.Margin = new Padding(4);
        feature4GroupBox.Padding = new Padding(8);
        feature4GroupBox.Text = "특성4";
        feature4ListBox.Dock = DockStyle.Fill;
        feature4ListBox.Enabled = false;
        feature4ListBox.Font = new Font("맑은 고딕", 10F);
        feature4ListBox.IntegralHeight = false;
        feature4ListBox.Name = "feature4ListBox";

        selectedLegoLabel.BorderStyle = BorderStyle.FixedSingle;
        selectedLegoLabel.Dock = DockStyle.Fill;
        selectedLegoLabel.Font = new Font("맑은 고딕", 10F, FontStyle.Bold);
        selectedLegoLabel.Margin = new Padding(4, 6, 4, 4);
        selectedLegoLabel.Name = "selectedLegoLabel";
        selectedLegoLabel.Padding = new Padding(10, 0, 0, 0);
        selectedLegoLabel.Text = "선택된 LEGO: -";
        selectedLegoLabel.TextAlign = ContentAlignment.MiddleLeft;

        callButtonPanel.Controls.Add(openButton);
        callButtonPanel.Controls.Add(insertButton);
        callButtonPanel.Controls.Add(editButton);
        callButtonPanel.Controls.Add(closeCallButton);
        callButtonPanel.Dock = DockStyle.Fill;
        callButtonPanel.FlowDirection = FlowDirection.LeftToRight;
        callButtonPanel.Padding = new Padding(0, 10, 0, 0);
        callButtonPanel.WrapContents = false;
        openButton.Height = 38;
        openButton.Margin = new Padding(0, 0, 10, 0);
        openButton.Text = "열기";
        openButton.Width = 110;
        insertButton.Height = 38;
        insertButton.Margin = new Padding(0, 0, 10, 0);
        insertButton.Text = "삽입";
        insertButton.Width = 110;
        editButton.Height = 38;
        editButton.Margin = new Padding(0, 0, 10, 0);
        editButton.Text = "수정";
        editButton.Width = 110;
        closeCallButton.Height = 38;
        closeCallButton.Margin = new Padding(0, 0, 10, 0);
        closeCallButton.Text = "닫기";
        closeCallButton.Width = 110;

        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1280, 760);
        Controls.Add(mainTabControl);
        MinimumSize = new Size(1050, 680);
        Name = "MainForm";
        Padding = new Padding(12);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "Project LEGO";
        mainTabControl.ResumeLayout(false);
        registrationTabPage.ResumeLayout(false);
        registrationLayout.ResumeLayout(false);
        registrationLayout.PerformLayout();
        registrationButtonPanel.ResumeLayout(false);
        callTabPage.ResumeLayout(false);
        callLayout.ResumeLayout(false);
        searchLayout.ResumeLayout(false);
        searchLayout.PerformLayout();
        selectionLayout.ResumeLayout(false);
        searchResultGroupBox.ResumeLayout(false);
        feature1GroupBox.ResumeLayout(false);
        feature2GroupBox.ResumeLayout(false);
        feature3GroupBox.ResumeLayout(false);
        feature4GroupBox.ResumeLayout(false);
        callButtonPanel.ResumeLayout(false);
        ResumeLayout(false);
    }

}
